services:
  - type: web
    name: nammabiz
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
