"""Add job messaging

Revision ID: 37e3e9c350ba
Revises: cbe8267fde3b
Create Date: 2026-09-29 02:45:10.919837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e3e9c350ba'
down_revision = 'cbe8267fde3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_messages_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_messages_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_job_messages_job_id'))

    op.drop_table('job_messages')
    # ### end Alembic commands ###
