"""Serialize contractor schedules

Revision ID: 9fc1e45dc443
Revises: 37e3e9c350ba
Create Date: 2026-09-29 02:57:13.218838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc1e45dc443'
down_revision = '37e3e9c350ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_column('schedule_version')

    # ### end Alembic commands ###
