"""Store Razorpay order IDs

Revision ID: a6b8b8c3fec2
Revises: 9fc1e45dc443
Create Date: 2026-09-29 03:23:34.990481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b8b8c3fec2'
down_revision = '9fc1e45dc443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('payment_lock_version', sa.Integer(), server_default='0', nullable=False))
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_order_id', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_payments_gateway_order_id', ['gateway_order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('payment_lock_version')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payments_gateway_order_id', type_='unique')
        batch_op.drop_column('gateway_order_id')

    # ### end Alembic commands ###
